### ISSUE TITLE
Update pages with changes from mockups

### ISSUE THREAD

**Issue by Saurutobi** [LbKStudios/mfsdb#16]
Mockups up to Reports have been updated. make sure the web page reflects that.

**Comment by Saurutobi** [comment]
done!

**Comment by Harmonickey** [comment]
nice!

On Thu, Apr 9, 2015 at 9:01 PM, Saurutobi <notifications@github.com> wrote:

> done!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LbKStudios/mfsdb/issues/16#issuecomment-91400675>.
>



-- 
Northwestern University Class of 2015
Weinberg College of Arts and Sciences, Computer Science Major
AAyerdi
*@u.northwestern.edu <http://u.northwestern.edu/>mobile: 1-269-267-3752*
