### ISSUE TITLE
Active Directory

### ISSUE THREAD

**Issue by hollywoodheinz** [LbKStudios/mfsdb#23]
Currently I am having tons of issues getting the login page to work and display, correctly. I don't know if this is due to IIS setting or issues or other specific issues. I have a feeling it is a mixture of bugs and permission errors. When I load the website from SUKI I am getting 401.2 Authentication denied error and when I am running it from the Windows Server 2008 VM I am getting a 404 error not found, I was also getting this error when I briefly tested it on the live server as well.(Its off the live server IIS at the moment). @Saurutobi  I really would like you to take a look at this for a couple moments in your free time.

**Comment by menglmaier** [comment]
ok, give me the teamviewer ID and password on ur pc and I'll look at it tonight after work. I removed that pc from my teamviewer a few weeks ago. I also suggest saving all ur data, checking in any code, and closing all programs because I have to log in under my BNetID.
